disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - type_body_length
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - type_name
  - large_tuple
  - trailing_whitespace
variable_name:
  min_length:
    warning: 2
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - 1SKConnect/Supporting File
  - R.generated.swift
  - Tests
